In [4]:
import numpy as np

#scalar arithmetric
array=np.array([1,2,3])
print(array-1)
print(array*3)
print(array**5)
print(array/3)


[0 1 2]
[3 6 9]
[  1  32 243]
[0.33333333 0.66666667 1.        ]


In [8]:
import numpy as np
#vectorized math function
array=np.array([1.01,2.34,3.09])
print(np.sqrt(array))
print(np.round(array))
print(np.pi)
print(np.floor(array))
print(np.ceil(array))




[1.00498756 1.52970585 1.75783958]
[1. 2. 3.]
3.141592653589793
[1. 2. 3.]
[2. 3. 4.]


In [10]:
import numpy as np
#vectorized math function
radii=np.array([1,2,3])
print(np.pi*radii**2)


[ 3.14159265 12.56637061 28.27433388]


In [13]:
import numpy as np
#elementwise artithmetric
array1=np.array([1,2,3])
array2=np.array([4,5,6])
print(array1+array2)
print(array1/array2)
print(array1*array2)
print(array1**array2)

[5 7 9]
[0.25 0.4  0.5 ]
[ 4 10 18]
[  1  32 729]


In [18]:
import numpy as np
#comparsion operator
scores=np.array([91,55,100,73,82,64])
print(scores==100)
print(scores>60)
scores[scores<60]=0
print(scores)


[False False  True False False False]
[ True False  True  True  True  True]
[ 91   0 100  73  82  64]
