In [ ]:
import numpy as np
# braodcasting allows numpy to perform operation on array 
#with diff shapes by virtaually expanding dimensions
#so they match the larger array's shape

#the deminsions have the same size
#OR
#one of the dimensions has a size of 1.

array1=np.array([[1,2,3,4]])
array2=np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)
print(array1*array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
import numpy as np


array1=np.array([[1,2,3,4],
                 [5,6,7,8]])
array2=np.array([[1],[2],[3],[4]])      # RULE X= eithier same number or one can be boardcasted
print(array1.shape)
print(array2.shape)
print(array1*array2)

(2, 4)
(4, 1)


ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

In [ ]:
array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

array2 = np.array([[1], [2], [3], [4]])          #RULE x , in action
print(array1.shape)
print(array2.shape)
print(array1*array2)

(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]
