In [2]:
#filtering = refering to the process of selecting elements
#            from an array that match a given condtion

In [4]:
import numpy as np
ages=np.array([[21,17,19,20,16,30,18,65],
               [39,22,15,99,18,19,20,21]])
teenagers=ages[ages<18]
adults=ages[(ages>=18) & (ages<65)]
print(adults)
print(teenagers)
adults=np.where(ages>=18, ages , 0)
print(adults)

[21 19 20 30 18 39 22 18 19 20 21]
[17 16 15]
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]
