In [21]:
import numpy as np
rng=np.random.default_rng()
print(rng.integers(1,7))
print(rng.integers(low=1, high=101,size=3))
print(rng.integers(low=1, high=101,size=(3,2)))


4
[16 81 67]
[[26 49]
 [46 94]
 [42 53]]


In [23]:
import numpy as np
rng=np.random.default_rng(seed=1)
print(rng.integers(1,7))
print(rng.integers(low=1, high=101,size=3))  #same as seed in minecraft
print(rng.integers(low=1, high=101,size=(3,2)))


3
[52 76 96]
[[ 4 15]
 [83 95]
 [25 32]]


In [30]:
import numpy as np
np.random.seed(seed=1)
print(np.random.uniform(low=-1, high=1,size=3))
print(np.random.uniform(low=-1, high=1,size=(3,2)))


[-0.16595599  0.44064899 -0.99977125]
[[-0.39533485 -0.70648822]
 [-0.81532281 -0.62747958]
 [-0.30887855 -0.20646505]]
