In [ ]:
import numpy as np

array=np.array([[1,2,3,4,],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])
#array[start:end:step]

#ROW SELECTION
print(array[0:4:2])
print(array[::-1])
#COLUMN SELECTION
print(array[:,0])
print(array[:,3])
print(array[:,-1])
print(array[:,0:3])
print(array[:,1::2])
#row and column ----> 1st row than column 
print(array[0:2,0:2])
print(array[0:2,2:4])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[ 1  5  9 13]
[ 4  8 12 16]
[ 4  8 12 16]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
