In [6]:
import numpy as np
#axes and multi-dimensional arrays
#image--->black and white(0 to 255)--->2D array
#image--->colored--->3D array(RGB)
#image ---->to print blue we filll RGB values as(0,0,255)
#R=0,G=0,B=255------>blue pixel
#1D----->1axis(axis=0)
#2D----->2axis (axis=0{row}, axis=1{column}) 
#3D----->3axis(axis=0(depth/layer), axis=1(row), axis=2(column))
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))
sum_of_columns=np.sum(arr2D, axis=0)
print("sum of columns:", sum_of_columns)
sum_of_rows=np.sum(arr2D, axis=1)
print("sum of rows:", sum_of_rows)
print(arr2D[0:2,1:2])  #rows from 0 to 1 and columns from 1 to 2

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
sum of columns: [12 15 18]
sum of rows: [ 6 15 24]
[[2]
 [5]]
