In [ ]:
import numpy as np
#3D array
arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])  
#2X3X2
print(arr3D, arr3D.shape)
#indexing
print(arr3D[1, 0, 1])  # Output: 8
#slicing
print(arr3D[:, 1, :])  # Output: [[ 3  4] [ 9 10]]
#replacing 


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
8
[[ 3  4]
 [ 9 10]]
