In [4]:
# vectorization 
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr*2)
print(arr+5)
print(arr**2)

[ 2  4  6  8 10]
[ 6  7  8  9 10]
[ 1  4  9 16 25]


In [ ]:
#broadcasting(scaling)
#rule1: they are equal, or
#rule2: one of them is 1
arr=np.array([[1,2,3],[4,5,6],[7,8,9],])
arr1=np.array([[1],[2],[3]])
print(arr+arr1)

arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr1=np.array([[1],[2],[3]])
print(arr+arr1)
#ERROR WLL BE HERE








[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


ValueError: operands could not be broadcast together with shapes (4,3) (3,1) 