In [2]:
#aggregation functions in numpy
import numpy as np
arr=np.array([[1,2,3,4,5]])
print(np.sum(arr))  #sum of all elements
print(np.prod(arr)) #product of all elements
print(np.mean(arr)) #mean of all elements
print(np.max(arr))  #maximum element
print(np.min(arr))  #minimum element
print(np.argmin(arr))  #index of minimum element
print(np.argmax(arr))  #index of maximum element
print(np.std(arr))     #standard deviation
print(np.median(arr))  #median
print(np.percentile(arr, 50)) #50th percentile


15
120
3.0
5
1
0
4
1.4142135623730951
3.0
3.0


In [4]:
#POWER FUNCTION
import numpy as np
arr=np.array([1,2,3,4,5])
print(np.power(arr, 3))  #cube of each element
print(np.sqrt(arr))      #square root of each element
print(np.cbrt(arr))      #cube root of each element
print(np.log(arr))       #natural logarithm of each element
print(np.log10(arr))     #base-10 logarithm of each element
print(np.log2(arr))      #base-2 logarithm of each element
print(np.exp(arr))       #exponential of each element


[  1   8  27  64 125]
[1.         1.41421356 1.73205081 2.         2.23606798]
[1.         1.25992105 1.44224957 1.58740105 1.70997595]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [5]:
#ROUNDING FUNCTIONS
import numpy as np
arr=np.array([1.2, 2.5, -3.7, 4.4, 5.9])
print(np.around(arr))   #round to nearest integer
print(np.floor(arr))    #round down to nearest integer
print(np.ceil(arr))     #round up to nearest integer
print(np.trunc(arr))    #truncate decimal part
print(np.rint(arr))     #round to nearest integer, .5 rounds to even
print(np.fix(arr))      #round towards zero
print(np.modf(arr))     #separate fractional and integer parts
print(np.unique(arr))  #find unique elements
print(np.sort(arr))    #sort the array
print(np.abs(arr))     #absolute values



[ 1.  2. -4.  4.  6.]
[ 1.  2. -4.  4.  5.]
[ 2.  3. -3.  5.  6.]
[ 1.  2. -3.  4.  5.]
[ 1.  2. -4.  4.  6.]
[ 1.  2. -3.  4.  5.]
(array([ 0.2,  0.5, -0.7,  0.4,  0.9]), array([ 1.,  2., -3.,  4.,  5.]))
[-3.7  1.2  2.5  4.4  5.9]
[-3.7  1.2  2.5  4.4  5.9]
[1.2 2.5 3.7 4.4 5.9]
