In [7]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr,type(arr))
arr2=np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
#needs to be rectangular , all rows must have same number of columns , if not error comes as inhomogeneous
print(arr2D,type(arr2D),arr2D.dtype,arr2D.shape)


[1 2 3 4 5] <class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] <class 'numpy.ndarray'> int64 (4, 3)


In [31]:
arr1=np.zeros((1,2),dtype="int64")
print(arr1,arr1.dtype,arr1.shape)

arr2=np.ones((1,2),dtype="int64")
print(arr2,arr2.dtype,arr2.shape)

arr3=np.full((3,4),100,)
print(arr3,arr3.dtype,arr3.shape)  

arr4=np.eye(3,4 ,dtype="int64")
print(arr4,arr4.dtype,arr4.shape) #identity matrix 

arr5=np.arange(1,10,2)
print(arr5,arr5.dtype,arr5.shape)

arr6=np.linspace(1,10,3)
print(arr6,arr6.dtype,arr6.shape)

[[0 0]] int64 (1, 2)
[[1 1]] int64 (1, 2)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] int64 (3, 4)
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]] int64 (3, 4)
[1 3 5 7 9] int64 (5,)
[ 1.   5.5 10. ] float64 (3,)
