In [ ]:
import numpy as np
#opearations on arrays
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
reshaped_arr=arr.reshape(3,2)
print(reshaped_arr)
#3x2-->2x3 ,possible only when total elements remain same
#3x2---->1x5 xxxxxx not possible
flattened_arr=arr.flatten()
print(flattened_arr) #2D array TO 1D array


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
