In [1]:
#Q1
import numpy as np

In [3]:
#Q2
print(np.__version__)

2.4.2


In [7]:
#Q3
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
#Q4
arr1=np.array([1,2,3,4])
print(arr1.nbytes)

32


In [ ]:
#Q5

array=np.array([1,2,3,4,5])
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [14]:
#q6 
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [17]:
#Q7
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
#Q8
arr=np.array([1,2,3,4])
print(arr[::-1])

[4 3 2 1]


In [27]:
#Q9
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Q10
arr=np.array([1,2,0,0,4,0])
x=arr[arr!=0]
print(x)
print(np.nonzero(arr))

[1 2 4]
(array([0, 1, 4]),)


In [1]:
#Q11
import numpy as np

arr = np.zeros((3,3))  # Create 3x3 zeros array
arr[0][0] = 1          # or use arr[0,0]
arr[1][1] = 1
arr[2][2] = 1
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
